import { Route } from 'react-router-dom'

export { default as Cart } from './cart'
export { default as Category } from './category'
export { default as Collocation } from './collocation'
export { default as Detail } from './detail'
export { default as Home } from './home'
export { default as My } from './my'
export { default as Login } from './login'
export { default as HomeIndex } from './home/home-index'
export { default as HomeDiscount } from './home/home-discount'
export { default as HomeWoman } from './home/home-woman'
export { default as HomeMan } from './home/home-man'
export { default as HomeChild } from './home/home-child'
export { default as HomeBaby } from './home/home-baby'
